
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# server.port=${PORT:8080}
server.port=${PORT:8080}

SPRING_DATASOURCE_URL=jdbc:postgresql://db.ikuujwpasuhujrwqelfw.supabase.co:5432/postgres
SPRING_DATASOURCE_USERNAME=bez-database
SPRING_DATASOURCE_PASSWORD=Uc?_.sTy7R!tD!K

spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
application.security.jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quannlnps41384@gmail.com
spring.mail.password=ulpi erba loic zaib
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

vnpay.tmnCode = 25NZ4WD8
vnpay.hashSecret = 5GXQ5WY7UHKRCP4IWA4C20BZ21J0OMCY
vnpay.refundApiUrl = https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
vnpay.apiUrl = https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

spring.profiles.active=dev

#spring.datasource.url=jdbc:sqlserver://localhost:50033;databaseName=bezshopapp;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=142500
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#application.security.jwt.secret-key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#application.security.jwt.expiration=86400000
#
## Spring Mail Configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=quannlnps41384@gmail.com
#spring.mail.password=ulpi erba loic zaib
#
#
## B?t bu?c cho Gmail
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## C?u h�nh VNPAY (D�ng key Sandbox ?? test)
#vnpay.tmnCode = 25NZ4WD8
#vnpay.hashSecret = 5GXQ5WY7UHKRCP4IWA4C20BZ21J0OMCY
#vnpay.apiUrl = https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#
## S?A L?I 2: ?�y PH?I L� API BACKEND ?? nh?n k?t qu?
## (Gi? s? b?n c� PaymentController b?t ? /api/v1/payment/vnpay-return)
#vnpay.returnUrl = http://localhost:8080/api/v1/payment/vnpay-return
#
## TH�M: ?�y m?i l� link FRONTEND m� Backend s? redirect v?
#vnpay.frontendReturnUrl = http://localhost:3000/order-confirmation
#
## TH�M: C?u h�nh API IPN (VNPAY g?i server-to-server)
## (Gi? s? b?n c� API /api/v1/payment/vnpay-ipn)
#vnpay.ipnUrl = http://localhost:8080/api/v1/payment/vnpay-ipn
